FROM alpine
ENTRYPOINT ["/bin/sh", "-c", "echo $0"]

# docker build -t echo-container .
# docker run --name my-echo --rm echo-container "Hello Hara San"
# docker run echo-container "Hello World"
# docker tag bb713da07197 typingliu/echo-container:latest
# docker push typingliu/echo-container:latest


